apiVersion: app/v1
 kind: Deployment
 spec:
  replicas: 1
 selector:
  matchLabels:
 app: app
 template:
 metadata:
 labels:
   app: app
 containers:
     - name: app
image: <image-registry-url>/app:latest
ports:
- containerPort: 80
resources:
  requests:
     memory: "128Mi"
     cpu: "100m"
  limits:
      memory: "512Mi"
      cpu: "500m"